export const FEATURED_EVENTS = [
  {
    id: "1",
    slug: "djangocon-europe-2025",
    title: "DjangoCon Europe 2025",
    image: "/images/event1.png",
    location: "Dublin, Ireland",
    date: "2025-06-04",
    time: "09:00 AM",
    description: "Annual Django conference with talks on REST APIs, PostgreSQL optimization, and Django 5.0 features.",
    category: "Conference",
    attendees: 520,
  },
  {
    id: "2",
    slug: "ai-edge-computing-hackathon-london",
    title: "AI Edge Computing Hackathon",
    image: "/images/event2.png",
    location: "London, UK",
    date: "2025-07-15",
    time: "10:00 AM",
    description: "Build AI models that run on Raspberry Pi and edge devices. Focus on TensorFlow Lite and computer vision.",
    category: "Hackathon",
    attendees: 160,
  },
  {
    id: "3",
    slug: "pycon-uk-2025",
    title: "PyCon UK 2025",
    image: "/images/event3.png",
    location: "Cardiff, Wales",
    date: "2025-09-19",
    time: "09:00 AM",
    description: "The UK's largest Python conference featuring AI, ML, web development, Django, and IoT talks.",
    category: "Conference",
    attendees: 850,
  },
  {
    id: "4",
    slug: "docker-kubernetes-workshop-manchester",
    title: "Docker & Kubernetes Workshop",
    image: "/images/event4.png",
    location: "Manchester, UK",
    date: "2025-06-10",
    time: "09:00 AM",
    description: "Hands-on workshop covering containerization, orchestration, and deploying Django apps with Docker Compose.",
    category: "Workshop",
    attendees: 55,
  },
  {
    id: "5",
    slug: "raspberry-pi-iot-meetup-london",
    title: "Raspberry Pi & IoT Meetup",
    image: "/images/event5.png",
    location: "London, UK",
    date: "2025-05-28",
    time: "06:30 PM",
    description: "Monthly meetup for makers and developers building IoT projects with Raspberry Pi, sensors, and Python.",
    category: "Meetup",
    attendees: 95,
  },
  {
    id: "6",
    slug: "llm-bootcamp-edinburgh",
    title: "LLM Application Bootcamp",
    image: "/images/event6.png",
    location: "Edinburgh, Scotland",
    date: "2025-08-12",
    time: "10:00 AM",
    description: "Intensive bootcamp on building production LLM applications with Python, LangChain, and vector databases.",
    category: "Workshop",
    attendees: 80,
  },
];

export const EVENT_CATEGORIES = [
  "All",
  "Conference",
  "Hackathon",
  "Meetup",
  "Workshop",
] as const;

export const TECH_STACK = [
  "Django",
  "Python",
  "Raspberry Pi",
  "Docker",
  "AI/ML",
  "PostgreSQL",
  "TensorFlow",
  "Computer Vision",
] as const;

export type EventCategory = typeof EVENT_CATEGORIES[number];
